//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExercicioModelFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livros()
        {
            this.LivroAutor = new HashSet<LivroAutores>();
        }
    
        public string LivroId { get; set; }
        public string Livro { get; set; }
        public string Tipo { get; set; }
        public string EditoraId { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<decimal> Adiantamento { get; set; }
        public Nullable<int> Royalty { get; set; }
        public Nullable<int> VendaAno { get; set; }
        public string Notas { get; set; }
        public System.DateTime DataPub { get; set; }
    
        public virtual Editoras Editora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LivroAutores> LivroAutor { get; set; }
    }
}
