//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExercicioModelFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LivroAutores
    {
        public string AutorId { get; set; }
        public string LivroId { get; set; }
        public Nullable<byte> Ordem { get; set; }
        public Nullable<int> TipoRoyalty { get; set; }
    
        public virtual Autores Autor { get; set; }
        public virtual Livros Livro { get; set; }
    }
}
