//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/ExemploServi%C3%A7o")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Preco {
            get {
                return this.PrecoField;
            }
            set {
                if ((this.PrecoField.Equals(value) != true)) {
                    this.PrecoField = value;
                    this.RaisePropertyChanged("Preco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Mensagem", ReplyAction="http://tempuri.org/IService1/MensagemResponse")]
        string Mensagem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Mensagem", ReplyAction="http://tempuri.org/IService1/MensagemResponse")]
        System.Threading.Tasks.Task<string> MensagemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Somar", ReplyAction="http://tempuri.org/IService1/SomarResponse")]
        int Somar(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Somar", ReplyAction="http://tempuri.org/IService1/SomarResponse")]
        System.Threading.Tasks.Task<int> SomarAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataHoraServidor", ReplyAction="http://tempuri.org/IService1/DataHoraServidorResponse")]
        System.DateTime DataHoraServidor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataHoraServidor", ReplyAction="http://tempuri.org/IService1/DataHoraServidorResponse")]
        System.Threading.Tasks.Task<System.DateTime> DataHoraServidorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OfertaDoDia", ReplyAction="http://tempuri.org/IService1/OfertaDoDiaResponse")]
        ExemploClient.ServiceReference1.Produto OfertaDoDia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OfertaDoDia", ReplyAction="http://tempuri.org/IService1/OfertaDoDiaResponse")]
        System.Threading.Tasks.Task<ExemploClient.ServiceReference1.Produto> OfertaDoDiaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ExemploClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ExemploClient.ServiceReference1.IService1>, ExemploClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Mensagem() {
            return base.Channel.Mensagem();
        }
        
        public System.Threading.Tasks.Task<string> MensagemAsync() {
            return base.Channel.MensagemAsync();
        }
        
        public int Somar(int a, int b) {
            return base.Channel.Somar(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SomarAsync(int a, int b) {
            return base.Channel.SomarAsync(a, b);
        }
        
        public System.DateTime DataHoraServidor() {
            return base.Channel.DataHoraServidor();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> DataHoraServidorAsync() {
            return base.Channel.DataHoraServidorAsync();
        }
        
        public ExemploClient.ServiceReference1.Produto OfertaDoDia() {
            return base.Channel.OfertaDoDia();
        }
        
        public System.Threading.Tasks.Task<ExemploClient.ServiceReference1.Produto> OfertaDoDiaAsync() {
            return base.Channel.OfertaDoDiaAsync();
        }
    }
}
